name: gendiff-auto-tests

on: push

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps: 
      - name: clone repo
        uses: actions/checkout@v4
      - name: install node.js
        uses: actions/setup-node@v4
        with:
          node-version: '>=20'
          cache: npm
      - name: installinng dependencies
        run: make install
      - name: auto tests
        run: make test
      - name: linting
        run: make lint
      - name: running an app
        run: 
          npm link
          gendiff ./__fixtures__/compareJSONFiles/file1.json ./__fixtures__/compareJSONFiles/file2.json
      - name: test and publish code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: make test_coverage
          debug: true
          coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov